-- Diego restaurant core schema
-- IMPORTANT: table names contain a hyphen and must always be double-quoted in SQL.

create extension if not exists pgcrypto;

create or replace function public.diego_is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (auth.jwt() -> 'app_metadata' ->> 'role') in ('admin', 'manager', 'cashier', 'kitchen'),
    false
  );
$$;

create table if not exists public."diego-products" (
  id uuid primary key default gen_random_uuid(),
  sku text unique,
  slug text not null unique,
  name text not null,
  description text,
  category text not null check (
    category in ('entrees', 'plats', 'grillades', 'accompagnements', 'desserts', 'boissons')
  ),
  price integer not null check (price >= 0),
  emoji text not null default '🍽️',
  image_path text,
  active boolean not null default true,
  in_stock boolean not null default true,
  signature boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public."diego-restaurant-tables" (
  id uuid primary key default gen_random_uuid(),
  label text not null unique,
  seats integer not null check (seats > 0),
  status text not null default 'libre' check (status in ('libre', 'occupee', 'reservee')),
  position_x numeric(5, 2) not null default 50 check (position_x between 0 and 100),
  position_y numeric(5, 2) not null default 50 check (position_y between 0 and 100),
  qr_token uuid not null unique default gen_random_uuid(),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public."diego-orders" (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  customer_id uuid references auth.users(id) on delete set null,
  channel text not null check (channel in ('comptoir', 'table', 'emporter', 'livraison')),
  status text not null default 'en_attente' check (
    status in ('en_attente', 'preparation', 'pret', 'servi', 'annule')
  ),
  restaurant_table_id uuid references public."diego-restaurant-tables"(id) on delete set null,
  payment_method text check (payment_method in ('especes', 'mobile_money', 'carte')),
  payment_status text not null default 'en_attente' check (
    payment_status in ('en_attente', 'paye', 'echoue', 'rembourse')
  ),
  customer_name text,
  customer_phone text,
  delivery_address text,
  scheduled_for timestamptz,
  note text,
  subtotal integer not null default 0 check (subtotal >= 0),
  total integer not null default 0 check (total >= 0),
  tracking_token uuid not null unique default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public."diego-order-items" (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public."diego-orders"(id) on delete cascade,
  product_id uuid references public."diego-products"(id) on delete set null,
  product_name text not null,
  unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity between 1 and 99),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public."diego-order-events" (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public."diego-orders"(id) on delete cascade,
  status text not null check (
    status in ('en_attente', 'preparation', 'pret', 'servi', 'annule')
  ),
  actor_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists "diego-products-category-active-idx"
  on public."diego-products"(category, active, in_stock, sort_order);
create index if not exists "diego-orders-status-created-idx"
  on public."diego-orders"(status, created_at);
create index if not exists "diego-orders-customer-idx"
  on public."diego-orders"(customer_id, created_at desc);
create index if not exists "diego-order-items-order-idx"
  on public."diego-order-items"(order_id);
create index if not exists "diego-order-events-order-idx"
  on public."diego-order-events"(order_id, created_at);

create or replace function public.diego_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists "diego-products-updated-at" on public."diego-products";
create trigger "diego-products-updated-at"
before update on public."diego-products"
for each row execute function public.diego_set_updated_at();

drop trigger if exists "diego-tables-updated-at" on public."diego-restaurant-tables";
create trigger "diego-tables-updated-at"
before update on public."diego-restaurant-tables"
for each row execute function public.diego_set_updated_at();

drop trigger if exists "diego-orders-updated-at" on public."diego-orders";
create trigger "diego-orders-updated-at"
before update on public."diego-orders"
for each row execute function public.diego_set_updated_at();

create or replace function public.diego_log_order_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or old.status is distinct from new.status then
    insert into public."diego-order-events" (order_id, status, actor_id)
    values (new.id, new.status, auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists "diego-orders-log-status" on public."diego-orders";
create trigger "diego-orders-log-status"
after insert or update of status on public."diego-orders"
for each row execute function public.diego_log_order_status();

-- Atomic customer checkout. Prices and product names are always taken from the database.
create or replace function public.diego_create_order(
  p_channel text,
  p_items jsonb,
  p_table_qr_token uuid default null,
  p_customer_name text default null,
  p_customer_phone text default null,
  p_delivery_address text default null,
  p_scheduled_for timestamptz default null,
  p_note text default null
)
returns table (id uuid, order_number bigint, tracking_token uuid, total integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_table_id uuid;
  v_expected integer;
  v_valid integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if p_channel not in ('table', 'emporter', 'livraison') then
    raise exception 'Invalid customer order channel';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Order must contain at least one item';
  end if;

  if p_channel = 'table' then
    select t.id into v_table_id
    from public."diego-restaurant-tables" t
    where t.qr_token = p_table_qr_token and t.active;

    if v_table_id is null then
      raise exception 'Invalid table QR code';
    end if;
  end if;

  v_expected := jsonb_array_length(p_items);

  select count(*) into v_valid
  from jsonb_to_recordset(p_items) as input(product_id uuid, quantity integer, note text)
  join public."diego-products" p on p.id = input.product_id
  where p.active and p.in_stock and input.quantity between 1 and 99;

  if v_valid <> v_expected then
    raise exception 'One or more products are invalid or unavailable';
  end if;

  insert into public."diego-orders" (
    customer_id,
    channel,
    restaurant_table_id,
    customer_name,
    customer_phone,
    delivery_address,
    scheduled_for,
    note
  )
  values (
    auth.uid(),
    p_channel,
    v_table_id,
    nullif(trim(p_customer_name), ''),
    nullif(trim(p_customer_phone), ''),
    nullif(trim(p_delivery_address), ''),
    p_scheduled_for,
    nullif(trim(p_note), '')
  )
  returning public."diego-orders".id into v_order_id;

  insert into public."diego-order-items" (
    order_id,
    product_id,
    product_name,
    unit_price,
    quantity,
    note
  )
  select
    v_order_id,
    p.id,
    p.name,
    p.price,
    input.quantity,
    nullif(trim(input.note), '')
  from jsonb_to_recordset(p_items) as input(product_id uuid, quantity integer, note text)
  join public."diego-products" p on p.id = input.product_id
  where p.active and p.in_stock;

  update public."diego-orders" o
  set
    subtotal = totals.amount,
    total = totals.amount
  from (
    select sum(oi.unit_price * oi.quantity)::integer as amount
    from public."diego-order-items" oi
    where oi.order_id = v_order_id
  ) totals
  where o.id = v_order_id;

  return query
  select o.id, o.order_number, o.tracking_token, o.total
  from public."diego-orders" o
  where o.id = v_order_id;
end;
$$;

revoke all on function public.diego_create_order(
  text, jsonb, uuid, text, text, text, timestamptz, text
) from public;
grant execute on function public.diego_create_order(
  text, jsonb, uuid, text, text, text, timestamptz, text
) to authenticated;

alter table public."diego-products" enable row level security;
alter table public."diego-restaurant-tables" enable row level security;
alter table public."diego-orders" enable row level security;
alter table public."diego-order-items" enable row level security;
alter table public."diego-order-events" enable row level security;

create policy "Public can view active Diego products"
on public."diego-products" for select
to anon, authenticated
using (active);

create policy "Staff manage Diego products"
on public."diego-products" for all
to authenticated
using (public.diego_is_staff())
with check (public.diego_is_staff());

create policy "Authenticated users view active Diego tables"
on public."diego-restaurant-tables" for select
to authenticated
using (active);

create policy "Staff manage Diego tables"
on public."diego-restaurant-tables" for all
to authenticated
using (public.diego_is_staff())
with check (public.diego_is_staff());

create policy "Customers view their Diego orders"
on public."diego-orders" for select
to authenticated
using (customer_id = auth.uid());

create policy "Staff manage Diego orders"
on public."diego-orders" for all
to authenticated
using (public.diego_is_staff())
with check (public.diego_is_staff());

create policy "Customers view their Diego order items"
on public."diego-order-items" for select
to authenticated
using (
  exists (
    select 1
    from public."diego-orders" o
    where o.id = order_id and o.customer_id = auth.uid()
  )
);

create policy "Staff manage Diego order items"
on public."diego-order-items" for all
to authenticated
using (public.diego_is_staff())
with check (public.diego_is_staff());

create policy "Customers view their Diego order events"
on public."diego-order-events" for select
to authenticated
using (
  exists (
    select 1
    from public."diego-orders" o
    where o.id = order_id and o.customer_id = auth.uid()
  )
);

create policy "Staff view Diego order events"
on public."diego-order-events" for select
to authenticated
using (public.diego_is_staff());

-- Existing bucket name supplied by the project owner.
insert into storage.buckets (id, name, public)
values ('diego bucket', 'diego bucket', true)
on conflict (id) do update set public = excluded.public;

create policy "Public can view Diego media"
on storage.objects for select
to public
using (bucket_id = 'diego bucket');

create policy "Staff upload Diego media"
on storage.objects for insert
to authenticated
with check (bucket_id = 'diego bucket' and public.diego_is_staff());

create policy "Staff update Diego media"
on storage.objects for update
to authenticated
using (bucket_id = 'diego bucket' and public.diego_is_staff())
with check (bucket_id = 'diego bucket' and public.diego_is_staff());

create policy "Staff delete Diego media"
on storage.objects for delete
to authenticated
using (bucket_id = 'diego bucket' and public.diego_is_staff());

-- Realtime tables. Run this migration once on a fresh project.
alter publication supabase_realtime add table public."diego-products";
alter publication supabase_realtime add table public."diego-restaurant-tables";
alter publication supabase_realtime add table public."diego-orders";
alter publication supabase_realtime add table public."diego-order-items";
alter publication supabase_realtime add table public."diego-order-events";
